CREATE TABLE PATRIMONIO
(
    NRO_TOMBO INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    DESCRICAO VARCHAR(120),
    MARCA_ID INT NOT NULL
)

CREATE TABLE MARCA
(
    MARCA_ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(120) UNIQUE NOT NULL,
)

CREATE TABLE USUARIO
(
    USUARIO_ID INT IDENTITY(1,1) PRIMARY KEY,
    NOME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(120) UNIQUE NOT NULL,
    SENHA VARCHAR(120) NOT NULL
)

ALTER TABLE PATRIMONIO
ADD CONSTRAINT FK_PATRIMONIO_MARCA
FOREIGN KEY (MARCA_ID) REFERENCES MARCA(MARCA_ID);